---
- name: Create a 2048-bit SSH key for user root
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/{{ ssh_key }}
  register: rsa_temp

- name: Add ssh_public_key 
  lineinfile: 
    dest: "{{ rsa_temp.home }}/.ssh/authorized_keys"
    line: "{{ rsa_temp.ssh_public_key }}"
    backup: yes


- name: Copy rsa file 
  fetch:
    src: "{{ rsa_temp.ssh_key_file }}"
    dest: ./
    flat: yes